<?php

/*
 * Xibo - Digital Signage - http://www.xibo.org.uk
 *
 * This file is part of Xibo - and is automatically generated by the installer
 *
 * You should not need to edit this file, unless your SQL connection details have changed.
 */

defined('XIBO') or die(__("Sorry, you are not allowed to directly access this page.") . "<br />" . __("Please press the back button in your browser."));

global $dbhost;
global $dbuser;
global $dbpass;
global $dbname;

$dbhost = '{{ .Env "MYSQL_HOST" }}';
$dbuser = 'admin';
$dbpass = '{{ .Env "MYSQL_PASS" }}';
$dbname = '{{ .Env "MYSQL_DBNAME" }}';

define('SECRET_KEY', '1XELF776S5bp');
